spring:
  application:
    name: payment-service
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: ${HOST_REDIS}
    port: ${PORT_REDIS}
server:
  port: 8084
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  service:
    yookassa:
      url: ${FEIGN_SERVICE_YOOKASSA}
      shop-id: ${YOOKASSA_SHOP_ID}
      secret: ${YOOKASSA_SECRET}