version: "3.8"

services:
  kafka:
    image: bitnamilegacy/kafka:4.0.0-debian-12-r10
    ports:
      - "9092:9092"
    environment:
      BITNAMI_DEBUG: true
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CLUSTER_ID: cc9f5eed9011
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9091
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9090,EXTERNAL://localhost:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  database:
    image: postgres:latest
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env 
  user-service:
    build: ../backend/user-service
    ports:
      - "8081:8081"
    env_file:
      - ../backend/user-service/.env
    depends_on:
      - kafka
      - database
    environment:
      SPRING_JWT_SECRET: ${JWT_SECRET}
      SPRING_EUREKA_CLIENT_SERVICE-URL: ${EUREKA_URL}
      SPRING_DATASOURCE_URL:  jdbc:postgresql://database:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
  cart-service:
    build: ../backend/cart-service
    ports:
      - "8082:8082"
    env_file:
      - ../backend/cart-service/.env
    depends_on:
      - kafka
      - database
    environment:
      SPRING_JWT_SECRET: ${JWT_SECRET}
      SPRING_EUREKA_CLIENT_SERVICE-URL: ${EUREKA_URL}
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
  storage-service:
    build: ../backend/storage-service
    ports:
      - "8080:8080"
    env_file:
      - ../backend/storage-service/.env
    depends_on:
      - kafka
      - database
  product-service:
    build: ../backend/product-service
    ports:
      - "8083:8083"
    env_file:
      - ../backend/product-service/.env
    depends_on:
      - kafka
      - database
    environment:
      SPRING_JWT_SECRET: ${JWT_SECRET}
      SPRING_EUREKA_CLIENT_SERVICE-URL: ${EUREKA_URL}
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
  payment-service:
    build: ../backend/payment-service
    ports:
      - "8084:8084"
    env_file:
      - ../backend/payment-service/.env
    depends_on:
      - redis
      - kafka
      - database
    environment:
      SPRING_JWT_SECRET: ${JWT_SECRET}
      SPRING_EUREKA_CLIENT_SERVICE-URL: ${EUREKA_URL}
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}   
